// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

//-------------------
import HelloController from './hello_controller';
application.register('hello', HelloController);

//-------------------
import ModalComponentController from './modal_controller';
application.register('modal', ModalComponentController);

//-------------

import RecipeMainController from './recipe_controller';
application.register('recipe', RecipeMainController);

//-------------

import MealPlanController from './meal_plan_controller';
application.register('mealplan', MealPlanController);
//-------------

import TurboModalController from './turbo_modal_controller';
application.register('turbo-modal', TurboModalController);
